# Generated by Django 6.0.4 on 2026-04-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_title", models.CharField(max_length=200)),
                ("post_desc", models.TextField()),
                (
                    "post_image",
                    models.ImageField(blank=True, null=True, upload_to="post_images/"),
                ),
                (
                    "post_category",
                    models.CharField(
                        choices=[
                            ("Technology", "Technology"),
                            ("Travel", "Travel"),
                            ("Wellness", "Wellness"),
                            ("Design", "Design"),
                            ("Science", "Science"),
                            ("Fiction", "Fiction"),
                            ("Philosophy", "Philosophy"),
                            ("Culture", "Culture"),
                        ],
                        max_length=100,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=300, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("role", models.CharField(default="Reader", max_length=50)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
