# Generated by Django 6.0.4 on 2026-05-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writesphere", "0003_category_alter_post_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
